openapi: 3.0.0
info:
  title: Recipes
  version: '1'
  description: >-
    Recipes is a simple tool for getting recipe information. It returns
    information on various recipes.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: support@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/recipe:
    get:
      summary: Recipes
      description: >-
        Recipes is a simple tool for getting recipe information. It returns
        information on various recipes.
      operationId: recipe
      tags:
        - 13
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
