openapi: 3.0.0
info:
  title: Country Boundaries
  version: '1'
  description: >-
    Country Boundaries is a simple tool for getting the shape of a specific
    country's border. It returns the shape of the specified country's border.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: support@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/countryboundaries:
    get:
      summary: Country Boundaries
      description: >-
        Country Boundaries is a simple tool for getting the shape of a specific
        country's border. It returns the shape of the specified country's
        border.
      operationId: countryboundaries
      tags:
        - 14
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
