openapi: 3.0.0
info:
  title: Chart Generator
  version: '1'
  description: >-
    Chart Generator is a simple tool for generating charts from data. It returns
    a URL to the generated image of the chart.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: support@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/chartgenerator:
    get:
      summary: Chart Generator
      description: >-
        Chart Generator is a simple tool for generating charts from data. It
        returns a URL to the generated image of the chart.
      operationId: chartgenerator
      tags:
        - 6
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
