openapi: 3.0.0
info:
  title: IP Blacklist Lookup
  version: '1'
  description: >-
    IP Blacklist Lookup is a simple tool for looking up if an IP address is in a
    blacklist. It returns if the IP is found in a blacklist.
  contact:
    name: APIVerve
    url: https://apiverve.com
    email: support@apiverve.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.apiverve.com
    description: Production server
security:
  - ApiKeyAuth: []
paths:
  /v1/ipblacklistlookup:
    get:
      summary: IP Blacklist Lookup
      description: >-
        IP Blacklist Lookup is a simple tool for looking up if an IP address is
        in a blacklist. It returns if the IP is found in a blacklist.
      operationId: ipblacklistlookup
      tags:
        - 17
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  data:
                    type: object
        '400':
          description: Bad Request - Invalid parameters
        '401':
          description: Unauthorized - Invalid or missing API key
        '429':
          description: Too Many Requests - Rate limit exceeded
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}
